website/views.py
from flask import Blueprint, render_template, request, json, redirect, url_for
import requests
from flask_login import login_required, current_user
from .models import  db, User, Trip
from flask_sqlalchemy import SQLAlchemy
import urllib3, re
from bs4 import BeautifulSoup
import re, os
from flask_restful import Resource, Api




views = Blueprint('views', __name__)

# ~~~~~ API KEYS ~~~~~~~~

mapquestKey = 'yourMapQuestKey'
OpenWeatherKey = 'yourOpenWeatherKey'


# ~~~~~~~ API ~~~~~~~~


@views.route('/api/trip/<int:mpg>/<HomeAddress>/<Destination>', methods=['GET','POST'])
def api_trip(mpg, HomeAddress, Destination):


    # ~~~ MAPQUEST API ~~~
    response = requests.get(f'http://www.mapquestapi.com/directions/v2/optimizedroute?key={mapquestKey}&json={{"locations":["{HomeAddress}","{Destination}"]}}')
    distance = round(response.json()['route']['distance'], 1)
    destinationlat = response.json()['route']['boundingBox']['lr']['lat']
    destinationlng = response.json()['route']['boundingBox']['lr']['lng']
    if mpg:
        fuel = round(int(distance)/int(mpg), 1)
    else:
        fuel = 'N/A'
    time = response.json()['route']['formattedTime']


    # ~~~ OPENWEATHER API ~~~
    response2 = requests.get(f'https://api.openweathermap.org/data/2.5/onecall?lat={destinationlat}&lon={destinationlng}&exclude=current,minutely,hourly,dailyalerts&appid={OpenWeatherKey}')
    jsonresponse = response2.json()


   # ~~~ AVERAGE GAS PRICES AUGUST 9TH, 2020 ~~~


    states = {'AK':'$3.69','AL':'2.84','AR':'2.87','AZ':'3.1','CA':'4.04','CO':'3.64','CT':'3.18','DC':'3.28','DE':'3.00','FL':'3.01', 'GA':'2.96',
            'HI':'4.09','IA':'3.02','ID':'3.81','IL':'3.38','IN':'3.12','KS':'2.94','KY':'2.93','LA':'2.83','MA':'3.05','MD':'3.05','ME':'3.11',
            'MI':'3.25','MN':'3.04','MO':'2.87','MS':'2.79','MT':'3.31','NC':'2.92','ND':'3.13','NE':'3.03','NH':'3.00','NJ':'3.20','NM':'3.08',
            'NV':'4.05','NY':'3.22','OH':'3.04','OK':'2.88','OR':'3.78','PA':'3.28','RI':'3.06','SC':'2.87','SD':'3.17','TN':'2.88','TX':'2.84',
            'UT':'3.86','VA':'2.97','VT':'3.09','WA':'3.89','WI':'3.04','WV':'3.05','WY':'3.58'}
    
    cityState = HomeAddress.split(',')
    rawState = cityState[1].upper()
    state = rawState.lstrip()
    for key,value in states.items():
        if key == state:
            cost = round(float(value) * float(fuel), 2)


    # ~~~ TEMPERATURES ~~~
    monday = weatherDataPull(jsonresponse, 0)
    tuesday = weatherDataPull(jsonresponse, 1)
    wensday = weatherDataPull(jsonresponse, 2)
    thursday = weatherDataPull(jsonresponse, 3)
    friday = weatherDataPull(jsonresponse, 4)
    saturday = weatherDataPull(jsonresponse, 5)
    sunday = weatherDataPull(jsonresponse, 6)

   
    return {'response': 200, 'results': [{'Origin': HomeAddress, 'Destination': Destination},
    {'Cost': '$ ' + str(cost), 'Distance': str(distance) + ' miles', 'Time': time, 'Fuel': str(fuel) + ' gallons'},
    {'Monday': {'Max Temp': str(monday[0]) + ' F', 'Min Temp': str(monday[1]) + ' F', 'Description': monday[3]}},
    {'Tuesday': {'Max Temp': str(tuesday[0]) + ' F', 'Min Temp': str(tuesday[1]) + ' F', 'Description': tuesday[3]}},
    {'Wensday': {'Max Temp': str(wensday[0]) + ' F', 'Min Temp': str(wensday[1]) + ' F', 'Description': wensday[3]}},
    {'Thursday': {'Max Temp': str(thursday[0]) + ' F', 'Min Temp': str(thursday[1]) + ' F', 'Description': thursday[3]}},
    {'Friday': {'Max Temp': str(friday[0]) + ' F', 'Min Temp': str(friday[1]) + ' F', 'Description': friday[3]}},
    {'Saturday': {'Max Temp': str(saturday[0]) + ' F', 'Min Temp': str(saturday[1]) + ' F', 'Description': saturday[3]}},
    {'Sunday': {'Max Temp': str(sunday[0]) + ' F', 'Min Temp': str(sunday[1]) + ' F', 'Description': sunday[3]}}]}



# ~~~~~~~~~ WEBSITE ~~~~~~~~~~

@views.route('/home')
@login_required
def home():
    allTrips = db.session.query(Trip).filter_by(user_id=current_user.id).all()

    return render_template('home.html', user=current_user, allTrips=allTrips)


@views.route('/Trip', methods=['GET','POST'])
@login_required
def startTrip():
    if request.method == 'POST':
        
        
        # ~~~ USER FORM INFO ~~~
        mpg = request.form.get("MPG")
        HomeAddress = request.form.get("Origin")
        Destination = request.form.get("Destination")

        

        # ~~~ MAPQUEST API ~~~
        response = requests.get(f'http://www.mapquestapi.com/directions/v2/optimizedroute?key={mapquestKey}&json={{"locations":["{HomeAddress}","{Destination}"]}}')
        distance = round(response.json()['route']['distance'], 1)
        destinationlat = response.json()['route']['boundingBox']['lr']['lat']
        destinationlng = response.json()['route']['boundingBox']['lr']['lng']
        if mpg:
            fuel = round(int(distance)/int(mpg), 1)
        else:
            fuel = 'N/A'
        time = response.json()['route']['formattedTime']


        # ~~~ OPENWEATHER API ~~~
        response2 = requests.get(f'https://api.openweathermap.org/data/2.5/onecall?lat={destinationlat}&lon={destinationlng}&exclude=current,minutely,hourly,dailyalerts&appid={OpenWeatherKey}')
        jsonresponse = response2.json()


        # ~~~ AVERAGE GAS PRICES AUGUST 9TH, 2020 ~~~


        states = {'AK':'$3.69','AL':'2.84','AR':'2.87','AZ':'3.1','CA':'4.04','CO':'3.64','CT':'3.18','DC':'3.28','DE':'3.00','FL':'3.01', 'GA':'2.96',
                'HI':'4.09','IA':'3.02','ID':'3.81','IL':'3.38','IN':'3.12','KS':'2.94','KY':'2.93','LA':'2.83','MA':'3.05','MD':'3.05','ME':'3.11',
                'MI':'3.25','MN':'3.04','MO':'2.87','MS':'2.79','MT':'3.31','NC':'2.92','ND':'3.13','NE':'3.03','NH':'3.00','NJ':'3.20','NM':'3.08',
                'NV':'4.05','NY':'3.22','OH':'3.04','OK':'2.88','OR':'3.78','PA':'3.28','RI':'3.06','SC':'2.87','SD':'3.17','TN':'2.88','TX':'2.84',
                'UT':'3.86','VA':'2.97','VT':'3.09','WA':'3.89','WI':'3.04','WV':'3.05','WY':'3.58'}
        
        cityState = HomeAddress.split(',')
        rawState = cityState[1].upper()
        state = rawState.lstrip()
        for key,value in states.items():
            if key == state:
                cost = round(float(value) * float(fuel), 2)

        # ~~~ TEMPERATURES ~~~
        
        monday = weatherDataPull(jsonresponse, 0)
        tuesday = weatherDataPull(jsonresponse, 1)
        wensday = weatherDataPull(jsonresponse, 2)
        thursday = weatherDataPull(jsonresponse, 3)
        friday = weatherDataPull(jsonresponse, 4)
        saturday = weatherDataPull(jsonresponse, 5)
        sunday = weatherDataPull(jsonresponse, 6)

        NewTrip = Trip(user_id=current_user.id, distance=distance, time=time, cost=cost, fuel=fuel, mpg=mpg, Destination=Destination, HomeAddress=HomeAddress, mondayMaxTemp=monday[0], mondayMinTemp=monday[1], mondayIcon=monday[2], mondayDescription=monday[3],tuesdayMaxTemp=tuesday[0], 
        tuesdayMinTemp=tuesday[1], tuesdayIcon=tuesday[2], tuesdayDescription=tuesday[3], wensdayMaxTemp=wensday[0], wensdayMinTemp=wensday[1], wensdayIcon=wensday[2], wensdayDescription=wensday[3],
        thursdayMaxTemp=thursday[0], thursdayMinTemp=thursday[1], thursdayIcon=thursday[2], thursdayDescription=thursday[3], fridayMaxTemp=friday[0], fridayMinTemp=friday[1], fridayIcon=friday[2], fridayDescription=friday[3],
        saturdayMaxTemp=saturday[0], saturdayMinTemp=saturday[1], saturdayIcon=saturday[2], saturdayDescription=saturday[3], sundayMaxTemp=sunday[0], sundayMinTemp=sunday[1], sundayIcon=sunday[2], sundayDescription=sunday[3])
        
        db.session.add(NewTrip)
        db.session.commit()   

        tripDescription = db.session.query(Trip).filter_by(user_id=current_user.id, cost=cost).first()
        return redirect(url_for(".currentTrip", id=tripDescription.id))
        
    return render_template('trip.html', user=current_user)



@views.route('/current-trip/<id>', methods=['GET','POST'])
def currentTrip(id):

    tripDescription = db.session.query(Trip).filter_by(user_id=current_user.id, id=id).first()
    if request.form.get("delete"):
        db.session.query(Trip).filter_by(user_id=current_user.id, id=id).delete()
        db.session.commit()
        return redirect(url_for(".home"))
    return render_template('current_trip.html', user=current_user, mapquestKey=mapquestKey, tripDescription=tripDescription)




# ~~~~~~~~~ FUNCTIONS ~~~~~~~~~~~


def KelvintoF(Kelvin):
    Fahrenheit = 1.8 * (Kelvin-273) + 32
    return round(Fahrenheit)



def weatherDataPull(jsonresponse, x):
    dataList = []
    mondaymaxKelvin = int(jsonresponse['daily'][x]['temp']['max'])
    mondayminKelvin = int(jsonresponse['daily'][x]['temp']['min'])
    maxTemp = KelvintoF(mondaymaxKelvin)
    minTemp = KelvintoF(mondayminKelvin)
    icon = jsonresponse['daily'][x]['weather'][0]['icon']
    description = jsonresponse['daily'][x]['weather'][0]['description']
    dataList.append(maxTemp)
    dataList.append(minTemp)
    dataList.append(icon)
    dataList.append(description)
    return dataList

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>ULTRATRIP</title>

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/styles.css" rel="stylesheet" />
        
        
    </head>
    <body>
        <div class="d-flex" id="wrapper" style="overflow-y:scroll">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light"><b>ULTRATRIP</b></div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/home">Dashboard</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/Trip">Start a Trip</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#">API</a>
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">|||</button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>
                                <li class="nav-item"><a class="nav-link" href="#!">Link</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="#!">Action</a>
                                        <a class="dropdown-item" href="#!">Another action</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="/logout">Logout</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid" style="height:200%">
                    {% block content %}
                    {% endblock %}    
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="static/scripts.js"></script>
    </body>
</html>

website/templates/current_trip.html
{% extends "base.html" %} {% block title %}Trip Results{% endblock %}
{% block content %}
<link href="/static/weathercard.css" rel="stylesheet" />
<br>


<div class="card4">
    <div class="row no-gutters">
        <div class="col-md-5">
            <img src="https://www.mapquestapi.com/staticmap/v5/map?start={{tripDescription.HomeAddress}}&end={{tripDescription.Destination}}&size=@2x&key={{mapquestKey}}"
                class="card-img">
        </div>
        <div class="col-md-7">
            <div class="card-body">
                <h5 class="card-title"><u>Trip Summary</u></h5>
                <ol class="gradient-list">
                    <li>
                        <div class="column"><b>&ensp;&ensp;&ensp;TOTAL TIME:</b></div>
                        <div class="column">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;{{ tripDescription.time }} </div>
                    </li>
                    <li>
                        <div class="column"><b>&ensp;&ensp;&ensp;DISTANCE:</b></div>
                        <div class="column">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;{{ tripDescription.distance }} Miles
                        </div>
                    </li>
                    <li>
                        <div class="column"><b>&ensp;&ensp;&ensp;FUEL USED:</b></div>
                        <div class="column">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;{{ tripDescription.fuel }} Gallons</div>
                    </li>
                    <li>
                        <div class="column"><b>&ensp;&ensp;&ensp;COST OF FUEL BASED OFF OF ORIGIN STATE AVERAGE:</b>
                        </div>
                        <div class="column">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;$ {{ tripDescription.cost }}</div>
                    </li>
                <br>
                <br>
                <br>
            </div>
        </div>
        <form method="POST">
            <button type="delete" name="delete" value="delete" class="btn btn-danger btn-lg float-right">Delete Trip</button>
        </form>
    </div>
</div>


<br>
<div class="column3">
    <div class="card2">
        <div class="card-body">
            7 Day Weather Forcast
        </div>
    </div>
</div>

<div class="card-group">
    <div class="card"> <span class="icon"><img class="img-fluid"
                src="http://openweathermap.org/img/wn/{{tripDescription.mondayIcon}}@2x.png"></span>
        <div class="title">
            <p>{{ tripDescription.Destination }}</p>
        </div>
        <div class="temp">{{ tripDescription.mondayDescription }}</div>
        <div class="row">
            <div class="col-6">
                <div class="header">HIGH</div>
                <div class="value">{{ tripDescription.mondayMaxTemp }}<sup>&deg;</sup></div>
            </div>
            <div class="col-6">
                <div class="header">LOW</div>
                <div class="value">{{ tripDescription.mondayMinTemp }}<sup>&deg;</sup></div>
            </div>
        </div>
    </div>
    <div class="card"> <span class="icon"><img class="img-fluid"
                src="http://openweathermap.org/img/wn/{{tripDescription.tuesdayIcon}}@2x.png"></span>
        <div class="title">
            <p>{{ tripDescription.Destination }}</p>
        </div>
        <div class="temp">{{ tripDescription.tuesdayDescription }}</div>
        <div class="row">
            <div class="col-6">
                <div class="header">HIGH</div>
                <div class="value">{{ tripDescription.tuesdayMaxTemp }}<sup>&deg;</sup></div>
            </div>
            <div class="col-6">
                <div class="header">LOW</div>
                <div class="value">{{ tripDescription.tuesdayMinTemp }}<sup>&deg;</sup></div>
            </div>
        </div>
    </div>
    <div class="card"> <span class="icon"><img class="img-fluid"
                src="http://openweathermap.org/img/wn/{{tripDescription.wensdayIcon}}@2x.png"></span>
        <div class="title">
            <p>{{ tripDescription.Destination }}</p>
        </div>
        <div class="temp">{{ tripDescription.wensdayDescription }}</div>
        <div class="row">
            <div class="col-6">
                <div class="header">HIGH</div>
                <div class="value">{{ tripDescription.wensdayMaxTemp }}<sup>&deg;</sup></div>
            </div>
            <div class="col-6">
                <div class="header">LOW</div>
                <div class="value">{{ tripDescription.wensdayMinTemp }}<sup>&deg;</sup></div>
            </div>
        </div>
    </div>
    <div class="card"> <span class="icon"><img class="img-fluid"
                src="http://openweathermap.org/img/wn/{{tripDescription.thursdayIcon}}@2x.png"></span>
        <div class="title">
            <p>{{ tripDescription.Destination }}</p>
        </div>
        <div class="temp">{{ tripDescription.thursdayDescription }}</div>
        <div class="row">
            <div class="col-6">
                <div class="header">HIGH</div>
                <div class="value">{{ tripDescription.thursdayMaxTemp }}<sup>&deg;</sup></div>
            </div>
            <div class="col-6">
                <div class="header">LOW</div>
                <div class="value">{{ tripDescription.thursdayMinTemp }}<sup>&deg;</sup></div>
            </div>
        </div>
    </div>
    <div class="card"> <span class="icon"><img class="img-fluid"
                src="http://openweathermap.org/img/wn/{{tripDescription.fridayIcon}}@2x.png"></span>
        <div class="title">
            <p>{{ tripDescription.Destination }}</p>
        </div>
        <div class="temp">{{ tripDescription.fridayDescription }}</div>
        <div class="row">
            <div class="col-6">
                <div class="header">HIGH</div>
                <div class="value">{{ tripDescription.fridayMaxTemp }}<sup>&deg;</sup></div>
            </div>
            <div class="col-6">
                <div class="header">LOW</div>
                <div class="value">{{ tripDescription.fridayMinTemp }}<sup>&deg;</sup></div>
            </div>
        </div>
    </div>
    <div class="card"> <span class="icon"><img class="img-fluid"
                src="http://openweathermap.org/img/wn/{{tripDescription.saturdayIcon}}@2x.png"></span>
        <div class="title">
            <p>{{ tripDescription.Destination }}</p>
        </div>
        <div class="temp">{{ tripDescription.saturdayDescription }}</div>
        <div class="row">
            <div class="col-6">
                <div class="header">HIGH</div>
                <div class="value">{{ tripDescription.saturdayMaxTemp }}<sup>&deg;</sup></div>
            </div>
            <div class="col-6">
                <div class="header">LOW</div>
                <div class="value">{{ tripDescription.saturdayMinTemp }}<sup>&deg;</sup></div>
            </div>
        </div>
    </div>
    <div class="card"> <span class="icon"><img class="img-fluid"
                src="http://openweathermap.org/img/wn/{{tripDescription.sundayIcon}}@2x.png"></span>
        <div class="title">
            <p>{{ tripDescription.Destination }}</p>
        </div>
        <div class="temp">{{ tripDescription.sundayDescription }}</div>
        <div class="row">
            <div class="col-6">
                <div class="header">HIGH</div>
                <div class="value">{{ tripDescription.sundayMaxTemp }}<sup>&deg;</sup></div>
            </div>
            <div class="col-6">
                <div class="header">LOW</div>
                <div class="value">{{ tripDescription.sundayMinTemp }}<sup>&deg;</sup></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock %}
{% block content %}

<br>
<div class="card text-center">
    <div class="card-header" style="background-color:aqua">
      
    </div>
    <div class="card-body">
      <h5 class="card-title" style="font-size:30px">WELCOME TO YOUR ULTRATRIP DASHBOARD</h5>
    </div>
    <div class="card-footer text-muted" style="background-color:aqua">
      
    </div>
  </div>
<br>
  <div class="card-group">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><u>Your Trips</u></h5>
        <p class="card-text"></p>
      </div>
    </div>
  </div>

<table id="example" class="table table-striped table-bordered" style="width:100%; background-color: rgb(253, 253, 253);">
    <thead>
        <tr>
            <th></th>
            <th class="text-secondary">ORIGIN</th>
            <th class="text-secondary">DESTINATION</th>
        </tr>
    </thead>
    <tbody>
        {% for trip in user.trip %}
        <tr>
            <td><a class="nav-item nav-link" href="{{url_for('views.currentTrip', id=trip.id)}}">( {{ trip.id }} )</a></td>
            <td>{{ trip.HomeAddress }}</td>
            <td>{{ trip.Destination }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

website/templates/login.html
<!DOCTYPE html>
<html>

<head>
   <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
   <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
   <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
   <!------ Include the above in your HEAD tag ---------->
</head>

<body>
   <link href="static/login.css" rel="stylesheet" />


   <div class="sidenav">
      <div class="login-main-text">
         <h2>Welcome to UltraTrip<br> Login Page</h2>
         <p>The ultimate trip Planning site</p>
      </div>
   </div>

   <div class="main">
      <div class="col-md-6 col-sm-12">
         <div class="login-form">
            <form method="POST">
               <div class="form-group">
                  <label>User Name</label>
                  <input type="text" name="userName" class="form-control" placeholder="User Name">
               </div>
               <div class="form-group">
                  <label>Password</label>
                  <input type="password" name="password" class="form-control" placeholder="Password">
               </div>
               <button type="submit" name="login" value="login" class="btn btn-black">Login</button>
               <button type="submit" name="register" value="register" class="btn btn-secondary">Register</button>
               {% with messages = get_flashed_messages(with_categories=true) %}
               {% if messages %}
               {% for category, message in messages %}
               {% if category == 'error' %}
               <div class="alert alert-danger alter dismissable fade show float-right" role="alert">
                  {{ message }}&nbsp;&nbsp;&nbsp;
                  <button type="button" class="close" data-dismiss="alert">
                     <span aria-hidden="true">&times;</span>
                  </button>
               </div>
               {% else %}
               <div class="alert alert-success alter dismissable fade show float-right" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert">
                     <span aria-hidden="true">&times;</span>
                  </button>
               </div>
               {% endif %}
               {% endfor %}
               {% endif %}
               {% endwith %}
            </form>
         </div>
      </div>
   </div>
</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
   integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
   integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
   integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>

website/templates/trip.html
{% extends "base.html" %} {% block title %}Start A Trip{% endblock %}
{% block content %}
<!-- Page content-->
<link href="static/styles.css" rel="stylesheet" />
<div class="row gutters-sm">
    <div class="form-body">
        <div class="row">
            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                        <h3>Enter Trip Information</h3>
                        <p>Fill in the data below.</p>
                        <form  method="POST" novalidate>

                            <div class="col-md-12">
                                <input class="form-control" type="text" name="MPG" placeholder="Car MPG (ex. 33)" required>
                                <br>

                            <div class="col-md-12">
                                <input class="form-control" type="text" name="Origin" placeholder="Origin (City, ST)" required>

                                <br>
                            <div class="col-md-12">
                                <input class="form-control" type="text" name="Destination" placeholder="Destination (City, ST)" required>
                                <br>

                                <div class="form-button mt-3">
                                    <button id="submit" type="submit"
                                    class="btn btn-primary">Submit</button>
                                       
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}